### ISSUE TITLE
namespaces

### ISSUE THREAD

**Issue by mbelatar** [umpirsky/twig-php-function#12]
`
			$extension = new \Umpirsky\Twig\Extension\PhpFunctionExtension();
			$extension->allowFunction('\Core\Helper::my_bold');

`

**Comment by mbelatar** [comment]
`<?php

namespace Core;

class Helper
{

	static function my_bold($str)
	{
		return "<strong>".$str."</strong>";
	}
}`

**Comment by mbelatar** [comment]
how to call My function \Core\Helper\my_bold() ???

**Comment by umpirsky** [comment]
It works only with PHP internal functions. It could work if you create a global function. It does not work with objects.
