### ISSUE TITLE
Allow twig >= 2.0

### ISSUE THREAD

**Issue by flo-sch** [umpirsky/twig-php-function#7]
I would like to use this extension in a Symfony project with twig locked to v2.2.0 because of some dependencies.

Maybe check it from your side aswell, but the code seems to be compatible with twig 2 without any required modification, it would just need to be allowed in composer.json, like `twig: ~1.12 || ~2.0` perhaps?

**Comment by umpirsky** [comment]
Fixed, thanks.

**Comment by flo-sch** [comment]
Good, thanks, could you please re-tag it (v0.1.1 ?), so I can start using it?

**Comment by umpirsky** [comment]
Just waiting to merge https://github.com/umpirsky/twig-php-function/pull/9 and I will.

**Comment by flo-sch** [comment]
Great :)

**Comment by umpirsky** [comment]
Done.

**Comment by flo-sch** [comment]
Excellent, it works perfectly fine indeed.

Thanks for your reactivity!

**Comment by umpirsky** [comment]
Glad it worked, thanks for using it. :+1:
